---
- name: Device Repair Provisioning
  hosts: all
  pre_tasks:
    - include: roles/common/pre_tasks/main.yml
  roles:
    - common
    - postgresql
    - flarior

- name: Device Repair Provisioning
  hosts: vagrant
  roles:
    - vagrant
