---
- name: install packages
  sudo: yes
  with_items: vagrant_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: configure vagrant account
  sudo: yes
  user:
    name: vagrant
    shell: /usr/bin/fish
    state: present

- name: clone repos
  with_items: flarior_repos
  git:
    repo: "https://github.com/flarior/{{ item.name }}"
    dest: "/vagrant/{{ item.name }}"
    accept_hostkey: yes
    update: no

- name: install vex
  sudo: yes
  pip:
    name: vex

- name: create virtual env
  shell: vex --make flarior pip install -U pip
  args:
    creates: ~/.virtualenvs/flarior

- name: install python packages
  shell: vex flarior pip install -r /vagrant/backend/requirements_dev.txt

- name: install node packages
  sudo: yes
  with_items: node_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install npm packages
  npm:
    path: /vagrant/frontend

- name: install bower packages
  shell: /vagrant/frontend/node_modules/bower/bin/bower install
  args:
    chdir: /vagrant/frontend

- name: fetch config repos
  with_items: vagrant_configs
  git:
    repo: "https://github.com/mekanix/{{ item.name }}"
    dest: "~/{{ item.name }}"
    accept_hostkey: yes
    update: no

- name: init config
  with_items: vagrant_configs
  shell: "~/{{ item.name }}/bin/init.sh"

- name: configure vagrant env
  template:
    src: local.fish.j2
    dest: ~/.config/fish/local.fish
