---
- name: clone repos
  with_items: flarior_repos
  git:
    repo: "https://github.com/flarior/{{ item.name }}"
    dest: "/vagrant/{{ item.name }}"
    accept_hostkey: yes
    update: no

- name: install python packages
  sudo: yes
  pip:
    requirements: /vagrant/backend/requirements_dev.txt

- name: install npm
  sudo: yes
  apt:
    pkg: npm
    state: latest

- name: install npm packages
  sudo: yes
  npm:
    path: /vagrant/frontend
    global: yes

- name: install npm extra packages
  sudo: yes
  with_items: npm_extra_packages
  npm:
    name: "{{ item.name }}"
    global: yes

- name: create initial user
  sudo: yes
  shell: "FLASK_CONFIG={{ flask_environment }} /vagrant/backend/manage.py create_user -e admin@example.com -p Sekrit"

- name: install packages
  sudo: yes
  with_items: vagrant_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: fetch config repos
  with_items: vagrant_configs
  git:
    repo: "https://github.com/mekanix/{{ item.name }}"
    dest: "~/{{ item.name }}"
    accept_hostkey: yes
    update: no
  notify:
    - init config

- name: configure flask env
  template:
    src: local.fish.j2
    dest: ~/.config/fish/local.fish

- name: add user vagrant
  sudo: yes
  user:
    name: vagrant
    shell: /usr/bin/fish
    state: present
