---
- name: install packages
  sudo: yes
  with_items: vagrant_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: clone repos
  with_items: flarior_repos
  git:
    repo: "https://github.com/flarior/{{ item.name }}"
    dest: "/vagrant/{{ item.name }}"
    accept_hostkey: yes
    update: no

- name: install python packages
  sudo: yes
  pip:
    requirements: /vagrant/backend/requirements_dev.txt

- name: install node packages
  sudo: yes
  with_items: node_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install npm packages
  npm:
    path: /vagrant/frontend

- name: install bower packages
  shell: /vagrant/frontend/node_modules/bower/bin/bower install
  args:
    chdir: /vagrant/frontend

- name: configure app
  template:
    src: local_config.py.j2
    dest: /vagrant/backend/local_config.py

- name: create DB tables
  shell: "FLASK_CONFIG={{ flask_environment }} /vagrant/backend/manage.py syncdb"

- name: create initial user
  sudo: yes
  shell: "FLASK_CONFIG={{ flask_environment }} /vagrant/backend/manage.py create_user -e admin@example.com -p Sekrit"

- name: fetch config repos
  with_items: vagrant_configs
  git:
    repo: "https://github.com/mekanix/{{ item.name }}"
    dest: "~/{{ item.name }}"
    accept_hostkey: yes
    update: no
  notify:
    - init config
    - configure flask env
    - configure vagrant account
