---
vagrant_packages:
  - name: cmake
  - name: fish
  - name: tmux
  - name: vim-nox

vagrant_configs:
  - name: fish
  - name: tmux
  - name: vim

flarior_repos:
  - name: backend
  - name: frontend
