---
- name: install packages
  sudo: yes
  with_items: postgresql_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: add postgresql service
  sudo: yes
  template:
    src: postgresql.service.j2
    dest: /lib/systemd/system/postgresql.service
    owner: root
    group: root
  notify:
    - restart postgresql

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: start postgresql
  sudo: yes
  service:
    name: postgresql
    enabled: yes
    state: restarted

- name: wait for postgresql
  wait_for:
    delay: 5
    port: 5432

- name: create user
  postgresql_user:
    name: "{{ flarior_postgresql_user }}"
    password: "{{ flarior_postgresql_password }}"
    login_host: 127.0.0.1
    login_user: "{{ flarior_postgresql_superuser }}"
    login_password: "{{ flarior_postgresql_superuser_password }}"

- name: create db
  postgresql_db:
    name: "{{ flarior_postgresql_db }}"
    encoding: UTF-8
    template: template0
    login_host: 127.0.0.1
    login_user: "{{ flarior_postgresql_superuser }}"
    login_password: "{{ flarior_postgresql_superuser_password }}"
    owner: "{{ flarior_postgresql_user }}"
